title: My Blog
description: Writing about things I find interesting
url: "https://hrbacek.github.io"

plugins:
  - jekyll-feed

kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

highlighter: rouge